services:
  discord-musicbot:
    build: .
    image: us-central1-docker.pkg.dev/trusty-anchor-442805-h7/quickstart-docker-repo/discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./config.js:/usr/src/app/config.js:ro

  lavalink:
    image: us-central1-docker.pkg.dev/trusty-anchor-442805-h7/quickstart-docker-repo/fredboat/lavalink:latest
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net:
